### ISSUE TITLE
Cannot login on instances with custom versions

### ISSUE THREAD

**Issue by raikasdev** [pkreissel/foryoufeed#3]
Trying to login with `https://mementomori.social` fails with `TypeError: Invalid Version: 4.2.0+nightly-2023-08-12~mementomori-social-mods + Mastodon Bird UI 1.7.1-nightly` from masto.js

This problem doesn't seem to occur in Masto.js v6, could you perhaps [update to it](https://github.com/neet/masto.js/releases/tag/v6.0.0)?

**Comment by pkreissel** [comment]
Working on it

**Comment by ronilaukkarinen** [comment]
@pkreissel It works!
